import Testing
import Foundation
@preconcurrency import FluentKit
@preconcurrency import FluentSQL
@testable import VaporUtilities
import SQLKit
import NIOEmbedded
import NIOCore
import Logging

// MARK: - Test Models

/// Parent model exercising `@Children`, `@Siblings`, and `@OptionalChild`.
final class House: Model, @unchecked Sendable {
    static let schema = "houses"
    static let space: String? = nil
    static let alias: String? = nil

    typealias IDValue = UUID

    @ID(key: .id)
    var id: UUID?

    @Field(key: "address")
    var address: String

    @Children(for: \.$house)
    var inhabitants: [Inhabitant]

    @OptionalChild(for: \.$house)
    var flagship: LandmarkInhabitant?

    @Siblings(through: HouseTag.self, from: \.$house, to: \.$tag)
    var tags: [Tag]

    required init() {}
}

/// A `@Children`-related model (has a `@Parent` back to `House`).
final class Inhabitant: Model, @unchecked Sendable {
    static let schema = "inhabitants"
    static let space: String? = nil
    static let alias: String? = nil

    typealias IDValue = UUID

    @ID(key: .id)
    var id: UUID?

    @Field(key: "name")
    var name: String

    @Field(key: "joined_at")
    var joinedAt: Date

    @Parent(key: "house_id")
    var house: House

    required init() {}
}

/// A `@OptionalChild`-related model (also used to test `@OptionalParent` from its side).
final class LandmarkInhabitant: Model, @unchecked Sendable {
    static let schema = "landmark_inhabitants"
    static let space: String? = nil
    static let alias: String? = nil

    typealias IDValue = UUID

    @ID(key: .id)
    var id: UUID?

    @Field(key: "title")
    var title: String

    @OptionalParent<House>(key: "house_id")
    var house: House?

    required init() {}
}

/// A pivot model for `@Siblings`.
final class HouseTag: Model, @unchecked Sendable {
    static let schema = "house_tags"
    static let space: String? = nil
    static let alias: String? = nil

    typealias IDValue = UUID

    @ID(key: .id)
    var id: UUID?

    @Parent(key: "house_id")
    var house: House

    @Parent(key: "tag_id")
    var tag: Tag

    required init() {}
}

/// The target of `@Siblings` (many-to-many).
final class Tag: Model, @unchecked Sendable {
    static let schema = "tags"
    static let space: String? = nil
    static let alias: String? = nil

    typealias IDValue = UUID

    @ID(key: .id)
    var id: UUID?

    @Field(key: "label")
    var label: String

    required init() {}
}

// MARK: - SQL Serialization Helpers

/// A minimal `Database` + `SQLDatabase` that only serializes SQL and never executes anything.
private final class EagerSerializerDB: Database, SQLDatabase {
    let logger = Logger(label: "test")
    let eventLoop: any EventLoop = NIOAsyncTestingEventLoop()
    let dialect: any SQLDialect = EagerPostgreSQLStyleDialect()
    let queryLogLevel: Logger.Level? = nil
    let context: DatabaseContext
    var inTransaction: Bool { false }

    init() {
        self.context = DatabaseContext(
            configuration: EagerConfig(),
            logger: Logger(label: "test"),
            eventLoop: NIOAsyncTestingEventLoop()
        )
    }

    func execute(sql query: any SQLExpression, _ onRow: @escaping @Sendable (any SQLRow) -> ()) -> EventLoopFuture<Void> {
        eventLoop.makeSucceededFuture(())
    }
    func execute(sql query: any SQLExpression, _ onRow: @escaping @Sendable (any SQLRow) -> ()) async throws {}

    func execute(query: DatabaseQuery, onOutput: @escaping @Sendable (any DatabaseOutput) -> ()) -> EventLoopFuture<Void> {
        eventLoop.makeSucceededFuture(())
    }
    func execute(schema: DatabaseSchema) -> EventLoopFuture<Void> { eventLoop.makeSucceededFuture(()) }
    func execute(enum: DatabaseEnum) -> EventLoopFuture<Void> { eventLoop.makeSucceededFuture(()) }
    func transaction<T>(_ closure: @escaping @Sendable (any Database) -> EventLoopFuture<T>) -> EventLoopFuture<T> { closure(self) }
    func withConnection<T>(_ closure: @escaping @Sendable (any Database) -> EventLoopFuture<T>) -> EventLoopFuture<T> { closure(self) }
}

/// Minimal PostgreSQL-style dialect so SQL serialization matches real Fluent output.
private struct EagerPostgreSQLStyleDialect: SQLDialect {
    var name: String { "psql" }
    var identifierQuote: any SQLExpression { SQLRaw("\"") }
    var literalStringQuote: any SQLExpression { SQLRaw("'") }
    var supportsAutoIncrement: Bool { true }
    var autoIncrementClause: any SQLExpression { SQLRaw("GENERATED BY DEFAULT AS IDENTITY") }
    var autoIncrementFunction: (any SQLExpression)? { nil }
    var literalDefault: any SQLExpression { SQLRaw("DEFAULT") }
    var supportsIfExists: Bool { true }
    var supportsDropBehavior: Bool { true }
    var supportsReturning: Bool { true }
    var triggerSyntax: SQLTriggerSyntax { .init() }
    var alterTableSyntax: SQLAlterTableSyntax { .init() }
    var upsertSyntax: SQLUpsertSyntax { .unsupported }
    var unionFeatures: SQLUnionFeatures { [] }
    var sharedSelectLockExpression: (any SQLExpression)? { SQLRaw("FOR SHARE") }
    var exclusiveSelectLockExpression: (any SQLExpression)? { SQLRaw("FOR UPDATE") }

    func bindPlaceholder(at position: Int) -> any SQLExpression { SQLRaw("$\(position)") }
    func literalBoolean(_ value: Bool) -> any SQLExpression { SQLRaw(value ? "true" : "false") }
    func customDataType(for: SQLDataType) -> (any SQLExpression)? { nil }
    func normalizeSQLConstraint(identifier: any SQLExpression) -> any SQLExpression { identifier }
    func nestedSubpathExpression(in column: any SQLExpression, for path: [String]) -> (any SQLExpression)? { nil }
}

/// Database configuration wiring an empty middleware array into the serializer DB.
private struct EagerConfig: DatabaseConfiguration {
    var middleware: [any AnyModelMiddleware] = []
    func makeDriver(for databases: Databases) -> any DatabaseDriver {
        struct D: DatabaseDriver {
            func makeDatabase(with context: DatabaseContext) -> any Database { EagerSerializerDB() }
            func shutdown() {}
        }
        return D()
    }
}

/// Serializes a `DatabaseQuery` to a SQL string via FluentSQL's converter.
private func serialize<M: FluentKit.Model>(_ query: QueryBuilder<M>) -> String {
    let converter = SQLQueryConverter(delegate: EagerConverterDelegate())
    let db = EagerSerializerDB()
    return db.serialize(converter.convert(query.query)).sql
}

/// Minimal delegate so the SQL converter can build without custom data types.
private struct EagerConverterDelegate: SQLConverterDelegate {
    func customDataType(_ kind: DatabaseSchema.DataType) -> (any SQLExpression)? { nil }
}

// MARK: - Tests

@Test("with + filter registers one eager loader")
func testFilteredWithRegistersLoader() {
    let db = EagerSerializerDB()
    let builder = House.query(on: db).with(\.$inhabitants) { inhabitants in
        inhabitants.filter(\.$joinedAt >= Date())
    }
    // One filtered loader should be pending on the builder after `.with(...)`.
    #expect(builder.eagerLoaders.count == 1)
}

@Test("Children: constraint is applied alongside the foreign key")
func filteredChildrenAppliesConstraint() {
    let db = EagerSerializerDB()
    let house = House()
    house.id = UUID()

    // Eager-load children, constraining the child query with a `joined_at` filter.
    let builder = House.query(on: db).with(\.$inhabitants) { children in
        children.filter(\.$joinedAt >= Date())
    }
    let loader = builder.eagerLoaders[0] as! FilteredEagerLoader<House, Inhabitant>

    // The serialized query must carry both the user filter and the FK back to `House`.
    let sql = serialize(loader.childQuery(models: [house], on: db))
    #expect(sql.contains(#""inhabitants"."joined_at""#))
    #expect(sql.contains(#">="#))
    #expect(sql.contains(#""inhabitants"."house_id""#))
}

@Test("OptionalChild: constraint is applied alongside the foreign key")
func filteredOptionalChildAppliesConstraint() {
    let db = EagerSerializerDB()
    let house = House()
    house.id = UUID()

    // Eager-load the to-one child with a title filter.
    let builder = House.query(on: db).with(\.$flagship) { child in
        child.filter(\.$title == "landmark")
    }
    let loader = builder.eagerLoaders[0] as! FilteredEagerLoader<House, LandmarkInhabitant>

    // The serialized query must carry both the user filter and the FK back to `House`.
    let sql = serialize(loader.childQuery(models: [house], on: db))
    #expect(sql.contains(#""landmark_inhabitants"."title""#))
    #expect(sql.contains("="))
    #expect(sql.contains(#""landmark_inhabitants"."house_id""#))
}

@Test("Parent: constraint is applied alongside the relation's ID filter")
func filteredParentAppliesConstraint() {
    let db = EagerSerializerDB()
    let inhabitant = Inhabitant()

    // Seed the `@Parent` FK so the eager query knows which `House` to fetch.
    inhabitant.$house.id = UUID()

    // Eager-load the related `House` with an address filter.
    let builder = Inhabitant.query(on: db).with(\.$house) { house in
        house.filter(\..$address == "1 Main")
    }
    let loader = builder.eagerLoaders[0] as! FilteredEagerLoader<Inhabitant, House>

    // The serialized query must carry both the user filter and the related-ID filter.
    let sql = serialize(loader.childQuery(models: [inhabitant], on: db))
    #expect(sql.contains(#""houses"."address""#))
    #expect(sql.contains(#""houses"."id""#))
}

@Test("OptionalParent: constraint is applied alongside the relation's ID filter")
func filteredOptionalParentAppliesConstraint() {
    let db = EagerSerializerDB()
    let landmark = LandmarkInhabitant()

    // Seed the optional parent FK so the eager query knows which `House` to fetch.
    landmark.$house.id = UUID()

    // Eager-load the optional `House` with an address filter.
    let builder = LandmarkInhabitant.query(on: db).with(\.$house) { house in
        house.filter(\..$address == "9 Elm")
    }
    let loader = builder.eagerLoaders[0] as! FilteredEagerLoader<LandmarkInhabitant, House>

    // The serialized query must carry both the user filter and the related-ID filter.
    let sql = serialize(loader.childQuery(models: [landmark], on: db))
    #expect(sql.contains(#""houses"."address""#))
    #expect(sql.contains(#""houses"."id""#))
}

@Test("Siblings: constraint is applied with the pivot join")
func siblingsAppliesConstraint() {
    let db = EagerSerializerDB()
    let house = House()
    house.id = UUID()

    // Eager-load the many-to-many tags with a label filter.
    let builder = House.query(on: db).with(\.$tags) { tags in
        tags.filter(\.$label == "featured")
    }
    let loader = builder.eagerLoaders[0] as! FilteredEagerLoader<House, Tag>

    // The serialized query must join the pivot and carry both filter and pivot FK.
    let sql = serialize(loader.childQuery(models: [house], on: db))
    #expect(sql.contains(#""tags"."label""#))
    #expect(sql.contains("JOIN"))
    #expect(sql.contains(#""house_tags"."house_id""#))
}

// MARK: - Conflict / Coexistence Tests

@Test("Plain, filtered, and withDeleted loads coexist on one query")
func mixedWithOverloadsCoexist() {
    let db = EagerSerializerDB()
    let house = House()
    house.id = UUID()

    // Combine Fluent's plain `with(_:)`, its `with(_:withDeleted:)`, and the new filtered forms.
    let builder = House.query(on: db)
        .with(\.$flagship)
        .with(\.$inhabitants) { children in
            children.filter(\..$joinedAt >= Date())
        }
        .with(\.$tags, withDeleted: true)

    // Plain + filtered-children + withDeleted-tags == three eager loaders.
    #expect(builder.eagerLoaders.count == 3)

    // The filtered children loader still carries both filter and FK.
    let childrenLoader = builder.eagerLoaders[1] as! FilteredEagerLoader<House, Inhabitant>
    let sql = serialize(childrenLoader.childQuery(models: [house], on: db))
    #expect(sql.contains(#""inhabitants"."joined_at""#))
    #expect(sql.contains(#""inhabitants"."house_id""#))
}

@Test("Multiple filtered relations register independently")
func multipleFilteredRelationsRegister() {
    let db = EagerSerializerDB()
    let house = House()
    house.id = UUID()

    // Two distinct filtered relations chained on the same outer query.
    let builder = House.query(on: db)
        .with(\.$inhabitants) { children in
            children.filter(\.$joinedAt >= Date())
        }
        .with(\.$tags) { tags in
            tags.filter(\.$label == "featured")
        }

    // Each filtered relation registers its own loader; neither overwrites the other.
    #expect(builder.eagerLoaders.count == 2)

    // Serialize each loader independently and confirm both constraints surface.
    let childrenSQL = serialize((builder.eagerLoaders[0] as! FilteredEagerLoader<House, Inhabitant>)
        .childQuery(models: [house], on: db))
    let tagsSQL = serialize((builder.eagerLoaders[1] as! FilteredEagerLoader<House, Tag>)
        .childQuery(models: [house], on: db))
    #expect(childrenSQL.contains(#""inhabitants"."joined_at""#))
    #expect(tagsSQL.contains(#""tags"."label""#))
}

@Test("Filtered load with nil parent IDs still applies the user filter")
func filteredLoadWithNilParentIDDegrades() {
    let db = EagerSerializerDB()
    // No id is set: the FK predicate becomes an empty `IN ()` (serializer emits `WHERE 1 = 0`),
    // but the user's filter column must still appear in the query.
    let house = House()

    let builder = House.query(on: db).with(\.$inhabitants) { children in
        children.filter(\.$joinedAt >= Date())
    }
    let loader = builder.eagerLoaders[0] as! FilteredEagerLoader<House, Inhabitant>

    let sql = serialize(loader.childQuery(models: [house], on: db))
    // The user filter is present even though the parent FK set is empty.
    #expect(sql.contains(#""inhabitants"."joined_at""#))
}