import Testing
import Foundation
@preconcurrency import FluentKit
@preconcurrency import FluentSQL
import VaporUtilities
import SQLKit
import NIOEmbedded
import NIOCore
import Logging

// MARK: - Test Helpers

/// A `Database` + `SQLDatabase` mock that captures the SQL of the last executed statement.
private final class RenameTestDB: Database, SQLDatabase, @unchecked Sendable {
    let logger = Logger(label: "test")
    let eventLoop: any EventLoop = NIOAsyncTestingEventLoop()
    let dialect: any SQLDialect
    let queryLogLevel: Logger.Level? = nil
    let context: DatabaseContext
    var inTransaction: Bool { false }

    private(set) var sql: String?

    init(dialect: any SQLDialect) {
        self.dialect = dialect
        self.context = DatabaseContext(
            configuration: RenameTestConfig(),
            logger: Logger(label: "test"),
            eventLoop: NIOAsyncTestingEventLoop()
        )
    }

    // MARK: SQLDatabase

    func execute(sql query: any SQLExpression, _ onRow: @escaping @Sendable (any SQLRow) -> ()) -> EventLoopFuture<Void> {
        self.sql = self.serialize(query).sql
        return self.eventLoop.makeSucceededFuture(())
    }

    func execute(sql query: any SQLExpression, _ onRow: @escaping @Sendable (any SQLRow) -> ()) async throws {
        self.sql = self.serialize(query).sql
    }

    // MARK: Database

    func execute(query: DatabaseQuery, onOutput: @escaping @Sendable (any DatabaseOutput) -> ()) -> EventLoopFuture<Void> {
        self.eventLoop.makeSucceededFuture(())
    }
    func execute(schema: DatabaseSchema) -> EventLoopFuture<Void> { self.eventLoop.makeSucceededFuture(()) }
    func execute(enum: DatabaseEnum) -> EventLoopFuture<Void> { self.eventLoop.makeSucceededFuture(()) }
    func transaction<T>(_ closure: @escaping @Sendable (any Database) -> EventLoopFuture<T>) -> EventLoopFuture<T> { closure(self) }
    func withConnection<T>(_ closure: @escaping @Sendable (any Database) -> EventLoopFuture<T>) -> EventLoopFuture<T> { closure(self) }
}

/// A `Database` mock that deliberately does not conform to `SQLDatabase`.
private final class NonSQLDatabase: Database, @unchecked Sendable {
    let logger = Logger(label: "test")
    let eventLoop: any EventLoop = NIOAsyncTestingEventLoop()
    let queryLogLevel: Logger.Level? = nil
    let context: DatabaseContext
    var inTransaction: Bool { false }

    init() {
        self.context = DatabaseContext(
            configuration: RenameTestConfig(),
            logger: Logger(label: "test"),
            eventLoop: NIOAsyncTestingEventLoop()
        )
    }

    func execute(query: DatabaseQuery, onOutput: @escaping @Sendable (any DatabaseOutput) -> ()) -> EventLoopFuture<Void> {
        self.eventLoop.makeSucceededFuture(())
    }
    func execute(schema: DatabaseSchema) -> EventLoopFuture<Void> { self.eventLoop.makeSucceededFuture(()) }
    func execute(enum: DatabaseEnum) -> EventLoopFuture<Void> { self.eventLoop.makeSucceededFuture(()) }
    func transaction<T>(_ closure: @escaping @Sendable (any Database) -> EventLoopFuture<T>) -> EventLoopFuture<T> { closure(self) }
    func withConnection<T>(_ closure: @escaping @Sendable (any Database) -> EventLoopFuture<T>) -> EventLoopFuture<T> { closure(self) }
}

/// A configurable `SQLDialect` so the same test double can emulate PostgreSQL, MySQL, SQLite,
/// and an unsupported dialect.
private struct RenameTestDialect: SQLDialect {
    let name: String
    let identifierQuote: any SQLExpression
    let literalStringQuote: any SQLExpression

    var supportsAutoIncrement: Bool { true }
    var autoIncrementClause: any SQLExpression { SQLRaw("GENERATED BY DEFAULT AS IDENTITY") }
    var autoIncrementFunction: (any SQLExpression)? { nil }
    var literalDefault: any SQLExpression { SQLRaw("DEFAULT") }
    var supportsIfExists: Bool { true }
    var supportsDropBehavior: Bool { true }
    var supportsReturning: Bool { true }
    var triggerSyntax: SQLTriggerSyntax { .init() }
    var alterTableSyntax: SQLAlterTableSyntax { .init() }
    var upsertSyntax: SQLUpsertSyntax { .unsupported }
    var unionFeatures: SQLUnionFeatures { [] }
    var sharedSelectLockExpression: (any SQLExpression)? { SQLRaw("FOR SHARE") }
    var exclusiveSelectLockExpression: (any SQLExpression)? { SQLRaw("FOR UPDATE") }

    func bindPlaceholder(at position: Int) -> any SQLExpression { SQLRaw("$\(position)") }
    func literalBoolean(_ value: Bool) -> any SQLExpression { SQLRaw(value ? "true" : "false") }
    func customDataType(for: SQLDataType) -> (any SQLExpression)? { nil }
    func normalizeSQLConstraint(identifier: any SQLExpression) -> any SQLExpression { identifier }
    func nestedSubpathExpression(in column: any SQLExpression, for path: [String]) -> (any SQLExpression)? { nil }

    static let postgres = RenameTestDialect(name: "postgresql", identifierQuote: SQLRaw("\""), literalStringQuote: SQLRaw("'"))
    static let mysql = RenameTestDialect(name: "mysql", identifierQuote: SQLRaw("`"), literalStringQuote: SQLRaw("'"))
    static let sqlite = RenameTestDialect(name: "sqlite", identifierQuote: SQLRaw("\""), literalStringQuote: SQLRaw("'"))
    static let unsupported = RenameTestDialect(name: "oracle", identifierQuote: SQLRaw("\""), literalStringQuote: SQLRaw("'"))
}

/// Database configuration wiring an empty middleware array into the test DBs.
private struct RenameTestConfig: DatabaseConfiguration {
    var middleware: [any AnyModelMiddleware] = []
    func makeDriver(for databases: Databases) -> any DatabaseDriver {
        struct D: DatabaseDriver {
            func makeDatabase(with context: DatabaseContext) -> any Database { RenameTestDB(dialect: RenameTestDialect.postgres) }
            func shutdown() {}
        }
        return D()
    }
}

// MARK: - Tests

@Test("renames a column on PostgreSQL with double-quoted identifiers")
func renameFieldPostgres() async throws {
    let db = RenameTestDB(dialect: RenameTestDialect.postgres)
    try await db.renameField("name", to: "full_name", on: "users")
    #expect(db.sql == #"ALTER TABLE "users" RENAME COLUMN "name" TO "full_name""#)
}

@Test("renames a column on MySQL with backtick identifiers")
func renameFieldMySQL() async throws {
    let db = RenameTestDB(dialect: RenameTestDialect.mysql)
    try await db.renameField("name", to: "full_name", on: "users")
    #expect(db.sql == "ALTER TABLE `users` RENAME COLUMN `name` TO `full_name`")
}

@Test("renames a column on SQLite")
func renameFieldSQLite() async throws {
    let db = RenameTestDB(dialect: RenameTestDialect.sqlite)
    try await db.renameField("name", to: "full_name", on: "users")
    #expect(db.sql == #"ALTER TABLE "users" RENAME COLUMN "name" TO "full_name""#)
}

@Test("accepts a non-string FieldKey such as .id")
func renameFieldKeyEnumCase() async throws {
    let db = RenameTestDB(dialect: RenameTestDialect.postgres)
    try await db.renameField(.id, to: "user_id", on: "users")
    #expect(db.sql == #"ALTER TABLE "users" RENAME COLUMN "id" TO "user_id""#)
}

@Test("throws notSQLDatabase for a non-SQL database")
func renameFieldNonSQL() async {
    let db = NonSQLDatabase()
    await #expect(throws: RenameFieldError.notSQLDatabase) {
        try await db.renameField("name", to: "full_name", on: "users")
    }
}

@Test("throws unsupportedDialect for dialects without RENAME COLUMN")
func renameFieldUnsupportedDialect() async {
    let db = RenameTestDB(dialect: RenameTestDialect.unsupported)
    await #expect(throws: RenameFieldError.unsupportedDialect("oracle")) {
        try await db.renameField("name", to: "full_name", on: "users")
    }
}
