import Testing
import Foundation
@preconcurrency import FluentKit
@preconcurrency import FluentSQL
@preconcurrency import VaporUtilities
import SQLKit
import NIOEmbedded
import NIOCore
import Logging

// MARK: - Test Models

final class Author: Model, @unchecked Sendable {
    static let schema = "authors"
    static let space: String? = nil
    static let alias: String? = nil

    typealias IDValue = UUID

    @ID(key: .id)
    var id: UUID?

    @Field(key: "name")
    var name: String

    @Children(for: \.$author)
    var posts: [Post]

    @OptionalChild(for: \.$author)
    var profile: Profile?

    required init() {}
}

final class Post: Model, @unchecked Sendable {
    static let schema = "posts"
    static let space: String? = nil
    static let alias: String? = nil

    typealias IDValue = UUID

    @ID(key: .id)
    var id: UUID?

    @Field(key: "title")
    var title: String

    @Field(key: "status")
    var status: String

    @Field(key: "created_at")
    var createdAt: Date

    @Parent(key: "author_id")
    var author: Author

    required init() {}
}

final class Profile: Model, @unchecked Sendable {
    static let schema = "profiles"
    static let space: String? = nil
    static let alias: String? = nil

    typealias IDValue = UUID

    @ID(key: .id)
    var id: UUID?

    @Field(key: "bio")
    var bio: String

    @OptionalParent<Author>(key: "author_id")
    var author: Author?

    required init() {}
}

/// A model with a `@Parent` relationship used for testing `whereHas` on parents.
final class Comment: Model, @unchecked Sendable {
    static let schema = "comments"
    static let space: String? = nil
    static let alias: String? = nil

    typealias IDValue = UUID

    @ID(key: .id)
    var id: UUID?

    @Field(key: "body")
    var body: String

    @Field(key: "is_approved")
    var isApproved: Bool

    @Parent(key: "post_id")
    var post: Post

    required init() {}
}

// MARK: - SQL Serialization Helpers

/// A bare-bones `Database` + `SQLDatabase` used only to serialize `SQLExpression` values to strings.
/// The `Database` conformance is required by `QueryBuilder`.
private final class SerializerDB: Database, SQLDatabase {
    let logger = Logger(label: "test")
    let eventLoop: any EventLoop = NIOAsyncTestingEventLoop()
    let dialect: any SQLDialect = PostgreSQLStyleDialect()
    let queryLogLevel: Logger.Level? = nil
    let context: DatabaseContext
    var inTransaction: Bool { false }

    init() {
        self.context = DatabaseContext(
            configuration: _Config(),
            logger: Logger(label: "test"),
            eventLoop: NIOAsyncTestingEventLoop()
        )
    }

    func execute(sql query: any SQLExpression, _ onRow: @escaping @Sendable (any SQLRow) -> ()) -> EventLoopFuture<Void> {
        eventLoop.makeSucceededFuture(())
    }
    func execute(sql query: any SQLExpression, _ onRow: @escaping @Sendable (any SQLRow) -> ()) async throws {}

    func execute(query: DatabaseQuery, onOutput: @escaping @Sendable (any DatabaseOutput) -> ()) -> EventLoopFuture<Void> {
        eventLoop.makeSucceededFuture(())
    }
    func execute(schema: DatabaseSchema) -> EventLoopFuture<Void> { eventLoop.makeSucceededFuture(()) }
    func execute(enum: DatabaseEnum) -> EventLoopFuture<Void> { eventLoop.makeSucceededFuture(()) }
    func transaction<T>(_ closure: @escaping @Sendable (any Database) -> EventLoopFuture<T>) -> EventLoopFuture<T> { closure(self) }
    func withConnection<T>(_ closure: @escaping @Sendable (any Database) -> EventLoopFuture<T>) -> EventLoopFuture<T> { closure(self) }
}

/// PostgreSQL-style dialect for SQL serialization in tests.
private struct PostgreSQLStyleDialect: SQLDialect {
    var name: String { "psql" }
    var identifierQuote: any SQLExpression { SQLRaw("\"") }
    var literalStringQuote: any SQLExpression { SQLRaw("'") }
    var supportsAutoIncrement: Bool { true }
    var autoIncrementClause: any SQLExpression { SQLRaw("GENERATED BY DEFAULT AS IDENTITY") }
    var autoIncrementFunction: (any SQLExpression)? { nil }
    var literalDefault: any SQLExpression { SQLRaw("DEFAULT") }
    var supportsIfExists: Bool { true }
    var supportsDropBehavior: Bool { true }
    var supportsReturning: Bool { true }
    var triggerSyntax: SQLTriggerSyntax { .init() }
    var alterTableSyntax: SQLAlterTableSyntax { .init() }
    var upsertSyntax: SQLUpsertSyntax { .unsupported }
    var unionFeatures: SQLUnionFeatures { [] }
    var sharedSelectLockExpression: (any SQLExpression)? { SQLRaw("FOR SHARE") }
    var exclusiveSelectLockExpression: (any SQLExpression)? { SQLRaw("FOR UPDATE") }

    func bindPlaceholder(at position: Int) -> any SQLExpression { SQLRaw("$\(position)") }
    func literalBoolean(_ value: Bool) -> any SQLExpression { SQLRaw(value ? "true" : "false") }
    func customDataType(for: SQLDataType) -> (any SQLExpression)? { nil }
    func normalizeSQLConstraint(identifier: any SQLExpression) -> any SQLExpression { identifier }
    func nestedSubpathExpression(in column: any SQLExpression, for path: [String]) -> (any SQLExpression)? { nil }
}

private struct _Config: DatabaseConfiguration {
    var middleware: [any AnyModelMiddleware] = []
    func makeDriver(for databases: Databases) -> any DatabaseDriver {
        struct D: DatabaseDriver {
            func makeDatabase(with context: DatabaseContext) -> any Database { SerializerDB() }
            func shutdown() {}
        }
        return D()
    }
}

/// Serialize a `DatabaseQuery` to a SQL string using the `FluentSQL` converter.
private func serializeQuery(_ query: DatabaseQuery) -> String {
    let delegate = TestSQLConverterDelegate()
    let converter = SQLQueryConverter(delegate: delegate)
    let expression = converter.convert(query)
    let db = SerializerDB()
    return db.serialize(expression).sql
}

/// A minimal delegate for `SQLQueryConverter` used in tests.
private struct TestSQLConverterDelegate: SQLConverterDelegate {
    func customDataType(_ dataType: DatabaseSchema.DataType) -> (any SQLExpression)? {
        nil
    }
}

// MARK: - whereHas: @Children

@Test("whereHas @Children with no closure generates EXISTS subquery")
func testWhereHasChildrenExistence() {
    let db = SerializerDB()
    let builder = Author.query(on: db).whereHas(\.$posts)
    let sql = serializeQuery(builder.query)
    #expect(sql.contains("EXISTS"))
    #expect(sql.contains("SELECT 1"))
    #expect(sql.contains(#""posts"."author_id""#))
    #expect(sql.contains(#""authors"."id""#))
}

@Test("whereHas @Children with filter generates EXISTS with additional WHERE")
func testWhereHasChildrenWithFilter() {
    let db = SerializerDB()
    let builder = Author.query(on: db)
        .whereHas(\.$posts) { post in post.filter(\.$status == "published") }
    let sql = serializeQuery(builder.query)
    #expect(sql.contains("EXISTS"))
    #expect(sql.contains(#""posts"."status""#))
}

@Test("whereHas @Children preserves parent filters")
func testWhereHasChildrenPreservesParentFilters() {
    let db = SerializerDB()
    let builder = Author.query(on: db)
        .filter(\.$name == "Alice")
        .whereHas(\.$posts) { post in post.filter(\.$status == "published") }
    let sql = serializeQuery(builder.query)
    #expect(sql.contains(#""authors"."name""#))
    #expect(sql.contains("EXISTS"))
}

@Test("whereHas @Children returns self for chaining")
func testWhereHasChildrenReturnsSelf() {
    let db = SerializerDB()
    let builder = Author.query(on: db)
    #expect(builder.whereHas(\.$posts) === builder)
}

// MARK: - whereDoesntHave: @Children

@Test("whereDoesntHave @Children generates NOT EXISTS subquery")
func testWhereDoesntHaveChildren() {
    let db = SerializerDB()
    let builder = Author.query(on: db).whereDoesntHave(\.$posts)
    let sql = serializeQuery(builder.query)
    #expect(sql.contains("NOT EXISTS"))
    #expect(sql.contains("SELECT 1"))
    #expect(sql.contains(#""posts"."author_id""#))
    #expect(sql.contains(#""authors"."id""#))
}

@Test("whereDoesntHave @Children with filter")
func testWhereDoesntHaveChildrenWithFilter() {
    let db = SerializerDB()
    let builder = Author.query(on: db)
        .whereDoesntHave(\.$posts) { post in post.filter(\.$status == "published") }
    let sql = serializeQuery(builder.query)
    #expect(sql.contains("NOT EXISTS"))
    #expect(sql.contains(#""posts"."status""#))
}

@Test("orWhereDoesntHave @Children adds OR NOT EXISTS")
func testOrWhereDoesntHaveChildren() {
    let db = SerializerDB()
    let builder = Author.query(on: db)
        .whereHas(\.$posts) { post in post.filter(\.$status == "published") }
        .orWhereDoesntHave(\.$posts) { post in post.filter(\.$status == "draft") }
    let sql = serializeQuery(builder.query)
    #expect(sql.contains("EXISTS"))
    #expect(sql.contains("NOT EXISTS"))
}

// MARK: - whereHas: @OptionalChild

@Test("whereHas @OptionalChild generates EXISTS subquery")
func testWhereHasOptionalChild() {
    let db = SerializerDB()
    let builder = Author.query(on: db).whereHas(\.$profile)
    let sql = serializeQuery(builder.query)
    #expect(sql.contains("EXISTS"))
    #expect(sql.contains("SELECT 1"))
    #expect(sql.contains(#""profiles"."author_id""#))
    #expect(sql.contains(#""authors"."id""#))
}

@Test("whereHas @OptionalChild with filter")
func testWhereHasOptionalChildWithFilter() {
    let db = SerializerDB()
    let builder = Author.query(on: db)
        .whereHas(\.$profile) { profile in profile.filter(\.$bio == "writer") }
    let sql = serializeQuery(builder.query)
    #expect(sql.contains("EXISTS"))
    #expect(sql.contains(#""profiles"."bio""#))
}

@Test("whereDoesntHave @OptionalChild generates NOT EXISTS")
func testWhereDoesntHaveOptionalChild() {
    let db = SerializerDB()
    let builder = Author.query(on: db).whereDoesntHave(\.$profile)
    let sql = serializeQuery(builder.query)
    #expect(sql.contains("NOT EXISTS"))
    #expect(sql.contains(#""profiles"."author_id""#))
    #expect(sql.contains(#""authors"."id""#))
}

// MARK: - whereHas: @Parent

@Test("whereHas @Parent generates EXISTS subquery on related table")
func testWhereHasParent() {
    let db = SerializerDB()
    // Post has a @Parent relationship to Author
    let builder = Post.query(on: db).whereHas(\.$author)
    let sql = serializeQuery(builder.query)
    #expect(sql.contains("EXISTS"))
    #expect(sql.contains("SELECT 1"))
    // Join condition: authors.id = posts.author_id
    #expect(sql.contains(#""authors"."id""#))
    #expect(sql.contains(#""posts"."author_id""#))
}

@Test("whereHas @Parent with filter")
func testWhereHasParentWithFilter() {
    let db = SerializerDB()
    let builder = Post.query(on: db)
        .whereHas(\.$author) { author in author.filter(\.$name == "Alice") }
    let sql = serializeQuery(builder.query)
    #expect(sql.contains("EXISTS"))
    #expect(sql.contains(#""authors"."name""#))
}

@Test("whereDoesntHave @Parent generates NOT EXISTS")
func testWhereDoesntHaveParent() {
    let db = SerializerDB()
    let builder = Post.query(on: db).whereDoesntHave(\.$author)
    let sql = serializeQuery(builder.query)
    #expect(sql.contains("NOT EXISTS"))
    #expect(sql.contains(#""authors"."id""#))
    #expect(sql.contains(#""posts"."author_id""#))
}

@Test("whereHas @Parent preserves existing filters")
func testWhereHasParentPreservesFilters() {
    let db = SerializerDB()
    let builder = Post.query(on: db)
        .filter(\.$status == "published")
        .whereHas(\.$author) { author in author.filter(\.$name == "Alice") }
    let sql = serializeQuery(builder.query)
    #expect(sql.contains(#""posts"."status""#))
    #expect(sql.contains(#""authors"."name""#))
    #expect(sql.contains("EXISTS"))
}

// MARK: - whereHas: @OptionalParent

@Test("whereHas @OptionalParent generates EXISTS subquery")
func testWhereHasOptionalParent() {
    let db = SerializerDB()
    // Profile has an @OptionalParent relationship to Author
    let builder = Profile.query(on: db).whereHas(\.$author)
    let sql = serializeQuery(builder.query)
    #expect(sql.contains("EXISTS"))
    #expect(sql.contains("SELECT 1"))
    #expect(sql.contains(#""authors"."id""#))
    #expect(sql.contains(#""profiles"."author_id""#))
}

@Test("whereHas @OptionalParent with filter")
func testWhereHasOptionalParentWithFilter() {
    let db = SerializerDB()
    let builder = Profile.query(on: db)
        .whereHas(\.$author) { author in author.filter(\.$name == "Alice") }
    let sql = serializeQuery(builder.query)
    #expect(sql.contains("EXISTS"))
    #expect(sql.contains(#""authors"."name""#))
}

@Test("whereDoesntHave @OptionalParent generates NOT EXISTS")
func testWhereDoesntHaveOptionalParent() {
    let db = SerializerDB()
    let builder = Profile.query(on: db).whereDoesntHave(\.$author)
    let sql = serializeQuery(builder.query)
    #expect(sql.contains("NOT EXISTS"))
    #expect(sql.contains(#""authors"."id""#))
    #expect(sql.contains(#""profiles"."author_id""#))
}

// MARK: - Integration: @Parent on a model that also has @Children

@Test("whereHas @Parent on Comment model")
func testWhereHasParentOnComment() {
    let db = SerializerDB()
    // Comment has a @Parent relationship to Post
    let builder = Comment.query(on: db)
        .whereHas(\.$post) { post in post.filter(\.$status == "published") }
    let sql = serializeQuery(builder.query)
    #expect(sql.contains("EXISTS"))
    #expect(sql.contains(#""posts"."id""#))
    #expect(sql.contains(#""comments"."post_id""#))
    #expect(sql.contains(#""posts"."status""#))
}

@Test("whereDoesntHave @Parent on Comment model")
func testWhereDoesntHaveParentOnComment() {
    let db = SerializerDB()
    let builder = Comment.query(on: db).whereDoesntHave(\.$post)
    let sql = serializeQuery(builder.query)
    #expect(sql.contains("NOT EXISTS"))
    #expect(sql.contains(#""posts"."id""#))
    #expect(sql.contains(#""comments"."post_id""#))
}

// MARK: - OR semantics

@Test("orWhereHas with no existing filters adds directly")
func testOrWhereHasNoExistingFilters() {
    let db = SerializerDB()
    let builder = Author.query(on: db)
        .orWhereHas(\.$posts) { post in post.filter(\.$status == "published") }
    let sql = serializeQuery(builder.query)
    // With no existing filters, OR is a no-op — just EXISTS
    #expect(sql.contains("EXISTS"))
    #expect(sql.contains(#""posts"."status""#))
}

@Test("orWhereHas with a parent filter produces (parent) OR EXISTS")
func testOrWhereHasWithParentFilter() {
    let db = SerializerDB()
    let builder = Author.query(on: db)
        .filter(\.$name == "Alice")
        .orWhereHas(\.$posts) { post in post.filter(\.$status == "published") }
    let sql = serializeQuery(builder.query)
    // Should produce: ("authors"."name" = $1) OR EXISTS (...)
    #expect(sql.contains("OR"))
    #expect(sql.contains(#""authors"."name""#))
    #expect(sql.contains("EXISTS"))
}

@Test("orWhereHas after whereHas produces (EXISTS A) OR (EXISTS B)")
func testOrWhereHasAfterWhereHas() {
    let db = SerializerDB()
    let builder = Author.query(on: db)
        .whereHas(\.$posts) { post in post.filter(\.$status == "published") }
        .orWhereHas(\.$posts) { post in post.filter(\.$status == "draft") }
    let sql = serializeQuery(builder.query)
    // Should produce: (EXISTS A) OR (EXISTS B)
    #expect(sql.contains("OR"))
    #expect(sql.contains("EXISTS"))
}

@Test("orWhereHas chained three times produces single OR group")
func testOrWhereHasChained() {
    let db = SerializerDB()
    let builder = Author.query(on: db)
        .whereHas(\.$posts) { post in post.filter(\.$status == "a") }
        .orWhereHas(\.$posts) { post in post.filter(\.$status == "b") }
        .orWhereHas(\.$posts) { post in post.filter(\.$status == "c") }
    let sql = serializeQuery(builder.query)
    // Should have a single OR group with 3 items, not nested groups
    #expect(sql.contains("OR"))
    #expect(sql.contains("EXISTS"))
}

@Test("orWhereHas with multiple parent filters produces (A AND B) OR EXISTS")
func testOrWhereHasMultipleParentFilters() {
    let db = SerializerDB()
    let builder = Author.query(on: db)
        .filter(\.$name == "Alice")
        .filter(\.$name == "Bob")
        .orWhereHas(\.$posts) { post in post.filter(\.$status == "published") }
    let sql = serializeQuery(builder.query)
    // Should produce: ("authors"."name" = $1 AND "authors"."name" = $2) OR EXISTS (...)
    #expect(sql.contains("OR"))
    #expect(sql.contains("EXISTS"))
}

@Test("orWhereDoesntHave with parent filter produces (parent) OR NOT EXISTS")
func testOrWhereDoesntHaveWithParentFilter() {
    let db = SerializerDB()
    let builder = Author.query(on: db)
        .filter(\.$name == "Alice")
        .orWhereDoesntHave(\.$posts) { post in post.filter(\.$status == "published") }
    let sql = serializeQuery(builder.query)
    #expect(sql.contains("OR"))
    #expect(sql.contains("NOT EXISTS"))
}

@Test("orWhereHas on @Parent produces correct OR SQL")
func testOrWhereHasParent() {
    let db = SerializerDB()
    let builder = Post.query(on: db)
        .filter(\.$status == "published")
        .orWhereHas(\.$author) { author in author.filter(\.$name == "Alice") }
    let sql = serializeQuery(builder.query)
    #expect(sql.contains("OR"))
    #expect(sql.contains("EXISTS"))
    #expect(sql.contains(#""authors"."name""#))
}

@Test("orWhereHas on @OptionalChild produces correct OR SQL")
func testOrWhereHasOptionalChild() {
    let db = SerializerDB()
    let builder = Author.query(on: db)
        .whereHas(\.$posts) { post in post.filter(\.$status == "published") }
        .orWhereHas(\.$profile) { profile in profile.filter(\.$bio == "writer") }
    let sql = serializeQuery(builder.query)
    #expect(sql.contains("OR"))
    #expect(sql.contains("EXISTS"))
    #expect(sql.contains(#""profiles"."bio""#))
}

@Test("orWhereDoesntHave @OptionalChild produces correct OR NOT EXISTS")
func testOrWhereDoesntHaveOptionalChild() {
    let db = SerializerDB()
    let builder = Author.query(on: db)
        .whereHas(\.$posts) { post in post.filter(\.$status == "published") }
        .orWhereDoesntHave(\.$profile) { profile in profile.filter(\.$bio == "writer") }
    let sql = serializeQuery(builder.query)
    #expect(sql.contains("OR"))
    #expect(sql.contains("NOT EXISTS"))
    #expect(sql.contains(#""profiles"."bio""#))
}

@Test("orWhereDoesntHave @Parent produces correct OR SQL")
func testOrWhereDoesntHaveParent() {
    let db = SerializerDB()
    let builder = Post.query(on: db)
        .whereHas(\.$author) { author in author.filter(\.$name == "Alice") }
        .orWhereDoesntHave(\.$author)
    let sql = serializeQuery(builder.query)
    #expect(sql.contains("OR"))
    #expect(sql.contains("NOT EXISTS"))
}

@Test("orWhereHas @OptionalParent produces correct OR SQL")
func testOrWhereHasOptionalParent() {
    let db = SerializerDB()
    let builder = Profile.query(on: db)
        .filter(\.$bio == "writer")
        .orWhereHas(\.$author) { author in author.filter(\.$name == "Alice") }
    let sql = serializeQuery(builder.query)
    #expect(sql.contains("OR"))
    #expect(sql.contains("EXISTS"))
    #expect(sql.contains(#""authors"."name""#))
}

@Test("orWhereDoesntHave @OptionalParent produces correct OR NOT EXISTS")
func testOrWhereDoesntHaveOptionalParent() {
    let db = SerializerDB()
    let builder = Profile.query(on: db)
        .filter(\.$bio == "writer")
        .orWhereDoesntHave(\.$author)
    let sql = serializeQuery(builder.query)
    #expect(sql.contains("OR"))
    #expect(sql.contains("NOT EXISTS"))
}

// MARK: - Custom ID key

@Test("whereHas @Children with custom ID key")
func testWhereHasCustomIDKey() {
    final class CustomIDModel: Model, @unchecked Sendable {
        static let schema = "custom_ids"
        static let space: String? = nil
        static let alias: String? = nil
        typealias IDValue = UUID

        @ID(custom: .string("custom_id"), generatedBy: .random)
        var id: UUID?

        @Children(for: \.$parent)
        var children: [CustomIDChild]

        required init() {}
    }

    final class CustomIDChild: Model, @unchecked Sendable {
        static let schema = "custom_children"
        static let space: String? = nil
        static let alias: String? = nil
        typealias IDValue = UUID

        @ID(key: .id)
        var id: UUID?

        @Parent(key: "custom_parent_id")
        var parent: CustomIDModel

        required init() {}
    }

    let db = SerializerDB()
    let builder = CustomIDModel.query(on: db).whereHas(\.$children)
    let sql = serializeQuery(builder.query)
    #expect(sql.contains("custom_id"))
    #expect(sql.contains("custom_parent_id"))
    #expect(sql.contains("EXISTS"))
}

@Test("whereDoesntHave @Children with custom ID key")
func testWhereDoesntHaveCustomIDKey() {
    final class CustomIDModel: Model, @unchecked Sendable {
        static let schema = "custom_ids"
        static let space: String? = nil
        static let alias: String? = nil
        typealias IDValue = UUID

        @ID(custom: .string("custom_id"), generatedBy: .random)
        var id: UUID?

        @Children(for: \.$parent)
        var children: [CustomIDChild]

        required init() {}
    }

    final class CustomIDChild: Model, @unchecked Sendable {
        static let schema = "custom_children"
        static let space: String? = nil
        static let alias: String? = nil
        typealias IDValue = UUID

        @ID(key: .id)
        var id: UUID?

        @Parent(key: "custom_parent_id")
        var parent: CustomIDModel

        required init() {}
    }

    let db = SerializerDB()
    let builder = CustomIDModel.query(on: db).whereDoesntHave(\.$children)
    let sql = serializeQuery(builder.query)
    #expect(sql.contains("NOT EXISTS"))
    #expect(sql.contains("custom_id"))
    #expect(sql.contains("custom_parent_id"))
}

// MARK: - Identity closure

@Test("whereHas identity closure produces same SQL as no closure")
func testWhereHasIdentityClosure() {
    let db = SerializerDB()
    let sql1 = serializeQuery(Author.query(on: db).whereHas(\.$posts).query)
    let sql2 = serializeQuery(Author.query(on: db).whereHas(\.$posts) { $0 }.query)
    #expect(sql1 == sql2)
}

@Test("whereDoesntHave identity closure produces same SQL as no closure")
func testWhereDoesntHaveIdentityClosure() {
    let db = SerializerDB()
    let sql1 = serializeQuery(Author.query(on: db).whereDoesntHave(\.$posts).query)
    let sql2 = serializeQuery(Author.query(on: db).whereDoesntHave(\.$posts) { $0 }.query)
    #expect(sql1 == sql2)
}